// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "GameplayTagContainer.h"
#include "NativeGameplayTags.h"



UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team_Player);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team_Monster);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Team_Monster_Boss);


UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM_TestMap);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM_MainTown);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM_Title);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM_Lobby);
// UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_BGM_Town);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_SFX);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_SFX_ATK_00);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Sound_SFX_ATK_01);