
#include "SKNativeGameplayTags.h"


UE_DEFINE_GAMEPLAY_TAG(TAG_Team, "Team");
UE_DEFINE_GAMEPLAY_TAG(TAG_Team_Player, "Team.Player");
UE_DEFINE_GAMEPLAY_TAG(TAG_Team_Monster, "Team.Monster");
UE_DEFINE_GAMEPLAY_TAG(TAG_Team_Monster_Boss, "Team.Monster.Boss");



UE_DEFINE_GAMEPLAY_TAG(TAG_Sound, "Sound");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_BGM, "Sound.BGM");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_BGM_TestMap,"Sound.BGM.TestMap");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_BGM_MainTown,"Sound.BGM.MainTown");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_BGM_Title,"Sound.BGM.Title");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_BGM_Lobby,"Sound.BGM.Lobby");


UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_SFX, "Sound.SFX");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_SFX_ATK_00,"Sound.SFX.ATK_00");
UE_DEFINE_GAMEPLAY_TAG(TAG_Sound_SFX_ATK_01,"Sound.SFX.ATK_01");
